apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: delete-secret-on-exit-
spec:
  serviceAccountName: argo-workflow
  entrypoint: main
  onExit: exit-handler
  templates:
  - name: main
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/git:latest
      command: [sh, -c]
      args:
        - |
          echo "Reading secret from environment variables..."
          echo "Username: $SECRET_USERNAME"
          echo "Password: $SECRET_PASSWORD"
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: test-onexit-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-onexit-secret
              key: password

  - name: exit-handler
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/bitnami/kubectl:latest
      command: [sh, -c]
      args:
        - |
          echo "Deleting secret test-onexit-secret..."
          kubectl delete secret test-onexit-secret -n argo
          echo "Secret deleted successfully"
  imagePullSecrets:
      - name: huawei-swr-image-pull-secret-model-gy