global:
  security:
    allowInsecureImages: true

argo-workflows:
  server:
    serviceType: NodePort
    authModes:
      - server
  artifactRepository:
    s3:
      bucket: argo-artifacts
      endpoint: argo-workflows-minio:9000
      insecure: true
      accessKeySecret:
        name: argo-workflows-minio
        key: root-user
      secretKeySecret:
        name: argo-workflows-minio
        key: root-password
  workflow:
    serviceAccount:
      create: true
      name: argo-workflow
    rbac:
      create: true
      rules:
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["delete"]

  controller:

    workflowNamespaces:
      - argo 
    workflowDefaults: 
      spec:
        ttlStrategy:
          secondsAfterCompletion: 604800 
        serviceAccountName: argo-workflow
        activeDeadlineSeconds: 7200 


minio:
  enabled: false
  console:
    enabled: false
  image:
    registry: docker.io
    repository: minio/minio
    tag: RELEASE.2025-09-07T16-13-09Z
  command:
    - minio
    - server
    - /bitnami/minio/data
    - --console-address
    - :9001
  auth:
    rootUser: minioadmin
    rootPassword: minioadmin
  volumePermissions:
    enabled: true
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
  volumes:
    mounts:
      - name: data
        mountPath: /bitnami/minio/data
  provisioning:
    enabled: true

    ## 2. Define buckets under provisioning.buckets
    buckets:
      - name: argo-artifacts
        region: us-east-1
        versioning: Suspended
        withLock: false